### ISSUE TITLE
Make profile page responsive

### ISSUE THREAD

**Issue by jescalada** [MLH-Fellowship/project-team-pythonic#21]
Currently the profile page doesn't adapt correctly to the size of the content in the cards. We should make this responsive using Bootstrap.

**Comment by Hgersten-hash** [comment]
I am working on it right now. I just created a new branch and plan on committing my updated profile page/css.

**Comment by Hgersten-hash** [comment]
Just fixed the sizes of the cards so that they can hold all of our information

**Comment by jescalada** [comment]
Fixed the alignment between the cards and the size of the profile picture to work on mobile devices.

**Comment by jescalada** [comment]
Finished improving the layout of the profile page to adapt with the new map.
